- name: Pasang Prometheus
  hosts: node1
  become: true
  roles:
    - prometheus.prometheus.prometheus
  vars:
    prometheus_scrape_configs:
      - job_name: prometheus
        static_configs:
          - targets: ['localhost:9090']
      - job_name: node_exporter
        static_configs:
          - targets:
              - '10.20.1.133:9100'
              - '10.20.1.52:9100'