- name: Naikkan stack pemantauan
  hosts: node1
  become: true
  vars:
    docker_users: [ubuntu]
  roles:
    - geerlingguy.docker
  tasks:
    - name: Cipta folder stack
      file:
        path: /opt/monitoring
        state: directory

    - name: Hantar prometheus.yaml
      copy:
        src: prometheus.yaml
        dest: /opt/monitoring/prometheus.yaml

    - name: Hantar compose.yaml
      copy:
        src: compose.yaml
        dest: /opt/monitoring/compose.yaml

    - name: Naikkan container
      command: docker compose up -d
      args:
        chdir: /opt/monitoring