services:
  profile:
    image: redis
    volumes:
      - me:/data

  server:
    image: ghcr.io/infratify/arena-server

  avatar:
    image: ghcr.io/infratify/arena-avatar
    ports:
      - "8080:8080"
    environment:
      NAME: AVATAR1
      COLOR: cyan
      SERVER: server:3000
    depends_on:
      - profile
      - server

volumes:
  me:
